volumes:
  clair-config:
services:
  pg:
    container_name: postgresql-clairv4
    environment:
      - POSTGRESQL_USER=clairuser
      - POSTGRESQL_PASSWORD=clairpass
      - POSTGRESQL_DATABASE=clair
      - POSTGRESQL_ADMIN_PASSWORD=adminpass
    image: registry.redhat.io/rhel8/postgresql-13:1-109
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  clair:
    container_name: clairv4
    restart: always
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - CLAIR_MODE=combo
      - CLAIR_CONF=/clair/compose-config.yaml
    image: registry.redhat.io/quay/clair-rhel8:v3.8.8
    volumes:
      - $CI_PROJECT_DIR/clair-config:/clair:Z



